server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: intracom-training-management

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=CTDTDH_INTRACOM;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    host: smtp.gmail.com
    port: 587
    username: hdung7047@gmail.com
    password: "hfbf fokc suxt njyj"
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          localhost: localhost

app:
  jwt:
    secret: IntracomTrainingSecretKey2024_MustBe32CharactersOrMore!
    expiration-ms: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha